### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by liamxg** [NicolaDM/mutSelSarsCov2#1]
Possible mutation events that would result into a stop codon
[[  0.   0.   0. 716.]
 [434.   0. 357. 381.]
 [221.   0.   0. 560.]
 [914.   0. 522.   0.]]
Numbers of 4-fold degenerate sites
[1226, 581, 276, 2155]
Frequencies at 4-fold degenerate sites
[0.2892873997168476, 0.13709296838131194, 0.06512505899008966, 0.5084945729117508]
New estimation of mutation rates, no approximations
Traceback (most recent call last):
  File "estimate_and_plot_rates.py", line 292, in <module>
    file=open(pathSimu+"mutations_13_11_20.tsv")
FileNotFoundError: [Errno 2] No such file or directory: './mutations_13_11_20.tsv'

**Comment by NicolaDM** [comment]
Hi,
To run these analyses you will need a file from matUtils/UShER listing all mutations for each node of the tree, for example

1	
Sample1	
2	
Sample2	T58A
3	
4	
5	
Sample3	
6	
7	
8	
Sample4	A8388G,T8987A
9	C9491T
...

and so on. I can ask my collaborators for the commands they used to get this file, but my understanding is that this should be straightforward given alignment data and UShER/matUtils.

**Comment by NicolaDM** [comment]
"mutations_13_11_20.tsv" is just the hard-coded name for this file I used in my analyses.

**Comment by NicolaDM** [comment]
But if you want to use the exact same file I used, you can accept the terms of GISAID use and contact me privately.

**Comment by liamxg** [comment]
I can accept the terms of GISAID. how to contact you, thanks.

**Comment by NicolaDM** [comment]
This is the manuscript that discuss this code/data/results: https://doi.org/10.1093/gbe/evab087 please find there the corresponding author information.

**Comment by LiXingguangBrandonStark** [comment]
thanks.
